/* Copyright (c) 2016 Grant Miner */
"use strict";
module.exports = {
  AIS: "Analog input voltage low alarm",
  ANT: "GPS antenna",
  BPL: "Backup battery low",
  BSI: "Bearer Setting Information",
  BTC: "Backup battery started charging",
  CAN: "Canbus information report",
  CFG: "Global Config",
  CRA: "Crash detection",
  DAT: "Transparent data transmission",
  DIS: "Digital inputs changed",
  DOG: "Protocol watchdog reboot",
  DOS: "Wave shape",
  EMG: "Emergency report mode",
  EPS: "External power supply voltage low",
  ERI: "Temperature sensor report",
  FLA: "Unusual fuel consuption",
  FRI: "Fixed report",
  FSD: "Digital fuel sensor report",
  GEO: "Geofence",
  GIN: "Entered geofence",
  GOT: "Left geofence",
  GSM: "GSM report",
  GSS: "GPS signal status",
  HBD: "Heartbeat",
  HBM: "Harsh acceleration or braking",
  HMC: "Hour meter counter",
  IDA: "iButton information report",
  IDF: "Idling off",
  IDN: "Excessive idling",
  IDL: "Excessive idling",
  IGF: "Ignition off",
  IGL: "Ignition location",
  IGN: "Ignition on",
  INF: "Device information report",
  IOB: "IO combination is set",
  JES: "Engine Info",
  JDC: "Jamming detection",
  JDR: "Jamming detected",
  JDS: "Jamming stopped",
  LBC: "Location by call",
  LSP: "Long stop",
  MON: "Stealthy voice monitoring",
  MPF: "Power disconnected",
  MPN: "Power connected",
  PDP: "GPRS connection",
  PDS: "Preserve special device logical state",
  PFA: "Power off",
  PNA: "Power on",
  RTL: "Manually requested position report",
  SOS: "SOS",
  SPD: "Speeding",
  SSR: "Start stop report",
  STC: "Backup battery stopped charging",
  STP: "Stop Alarm",
  STR: "Start Alarm",
  STT: "Motion Alarm",
  TMA: "Time adjustment",
  TMP: "Temperature",
  TOW: "Towing",
  OBD: "OBD-II status",
  OPN: "OBD-II power on",
  OPF: "OBD-II power off",
  ORR: "OBD-II real-time request",
  OSM: "OBD-II status monitor",
  OWH: "Outside working hours",
  PIN: "Auto-unlock PIN",
  QSS: "Quick Start Setting",
  RTO: "Real-time operation",
  SRI: "Server Register Information",
  WLT: "White list"
};
